set.seed(1)
library(CellID)
library(Seurat)
library(splatter)
library(scater)
library(tidyverse)
library(foreach)
library(irlba)
library(magrittr)
library(ComplexHeatmap)
library(FastKNN)
library(cowplot)
library(ggpubr)
library(grid)
library(gtable)
library(pbmcapply)
library(doMC)
registerDoMC(cores = 50)
